### ISSUE TITLE
Template style pastas with arguments

### ISSUE THREAD

**Issue by wschnicke** [njha7/Flamingo#1]
A pasta which can take arguments.

Example:

> ~pasta_template get nice! "Tyler is a Java Chad"
`from: jassy@amazon.com`
`subject: Tyler is a Java Chad`
`body:`
`nice!`

**Comment by njha7** [comment]
Flamingo is deprecated. See [FlamingoV2](https://github.com/njha7/FlamingoV2) for the latest updates.
